name: Check Has Semver Label

on:
  workflow_call:
    inputs:
      pull-request:
        type: string
        description: The stringified PR JSON payload.
        required: false
      skip:
        type: boolean
        description: Whether to skip the workflow or not.
        required: false
        default: false
    outputs:
      matched-label:
        description: The matched semantic versioning label. There will only be one.
        value: ${{ jobs.check-has-semver-label.outputs.matched-label }}

permissions:
  pull-requests: write

env:
  status-report-action-repository: infrastructure-blocks/check-has-semver-label-workflow

jobs:
<<<<<<< HEAD
  check-has-semver-label:
    if: ${{ !inputs.skip }}
=======
  example-job:
>>>>>>> template/master
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    outputs:
      matched-label: ${{ fromJson(steps.check-labels.outputs.matched-labels)[0] }}
    steps:
<<<<<<< HEAD
      - if: ${{ inputs.pull-request == '' }}
        id: current-pr
        uses: infrastructure-blocks/get-current-pull-request-action@v1
      - id: parse-inputs
=======
      # This condition should be on every step.
      - if: ${{ !inputs.skip }}
        id: example-step
        name: Example step
>>>>>>> template/master
        env:
          ISSUE_JSON: ${{ inputs.pull-request || steps.current-pr.outputs.json }}
        run: |
          if test "${{ runner.debug }}" = "1"; then
            set -x
          fi
      
          echo "issue=${ISSUE_JSON}" >> ${GITHUB_OUTPUT}
      - uses: infrastructure-blocks/status-report-action@v1
        with:
          mode: clear
          issue-number: ${{ fromJson(steps.parse-inputs.outputs.issue).number }}
      - uses: docker://public.ecr.aws/infrastructure-blocks/check-labels-action:v2
        id: check-labels
        with:
          pull-request: ${{ steps.parse-inputs.outputs.issue }}
          exactly-once: '["^no version$", "^patch$", "^minor$", "^major$"]'
      - if: ${{ failure() }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          issue-number: ${{ fromJson(steps.parse-inputs.outputs.issue).number }}
          body: |
            :boom: **Error**: expecting exactly one semantic versioning PR label. Please provide one of "no version", "patch", "minor", "major"
